# Generated by Django 5.0.6 on 2024-05-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_manager_product_order_productinorder_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product_count',
            field=models.IntegerField(),
        ),
    ]
