# Generated by Django 5.0.6 on 2024-05-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, through='shop.ProductInCart', to='shop.product'),
        ),
    ]
