# Generated by Django 5.0.6 on 2024-05-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='product_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
