# Generated by Django 5.0.6 on 2024-05-27 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productincart_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products_in_cart', through='shop.ProductInCart', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='products_in_order', through='shop.ProductInOrder', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_in_cart_fields', to='shop.cart'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_in_cart_fields', to='shop.product'),
        ),
    ]
