# Generated by Django 5.0.6 on 2024-05-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_cart_products_alter_order_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='productincart',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='productincart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='return',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='return',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='return',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='return',
            old_name='product_id',
            new_name='product',
        ),
    ]
