# Generated by Django 5.0.6 on 2024-05-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_client_id_cart_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='1-я Красноармейская, д.1/21', max_length=255),
            preserve_default=False,
        ),
    ]
