# Generated by Django 5.0.6 on 2024-05-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.client'),
        ),
        migrations.AlterField(
            model_name='return',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.manager'),
        ),
        migrations.AlterField(
            model_name='return',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.order'),
        ),
        migrations.AlterField(
            model_name='return',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product'),
        ),
    ]
