# Generated by Django 5.0.6 on 2024-06-02 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_return_client_alter_return_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products_in_cart', through='shop.ProductInCart', to='shop.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=255, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('PACK', 'packing'), ('OTW', 'on the way'), ('DELD', 'delivered'), ('CANC', 'canceled')], default='PACK', max_length=4, verbose_name='Статус доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.manager', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='products_in_order', through='shop.ProductInOrder', to='shop.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_count',
            field=models.IntegerField(default=0, verbose_name='Доступное количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=20, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_in_cart_fields', to='shop.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_in_cart_fields', to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='product_count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product_count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='return',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='return',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='return',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.manager', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='return',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='return',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.TextField(verbose_name='Причина возврата'),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ACCEPT', 'accepted'), ('DECLINE', 'declined')], default='PENDING', max_length=7, verbose_name='Статус возврата'),
        ),
    ]
